### ISSUE TITLE
HttpConnectionImpl.java:97 IllegalStateException: Already connected

### ISSUE THREAD

**Issue by yegamega** [shinovon/KEmulator#100]
>>java.lang.IllegalStateException: Already connected
>>	at sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(Unknown Source)
>>	at javax.microedition.io.HttpConnectionImpl.connect(HttpConnectionImpl.java:97)
>>	at javax.microedition.io.HttpConnectionImpl.openInputStream(HttpConnectionImpl.java:215)
>>	at javax.microedition.io.HttpConnectionImpl.openDataInputStream(HttpConnectionImpl.java:210)
>>	at d.Code(Unknown Source)
>>	at d.M(Unknown Source)
>>	at d.run(Unknown Source)
>>	at java.lang.Thread.run(Unknown Source)

**Comment by shinovon** [comment]
Which app? Any steps to reproduce?

**Comment by yegamega** [comment]
@shinovon opera mini
