### ISSUE TITLE
Harry Potter 3 (low-end versions) LCDUI menu reset

### ISSUE THREAD

**Issue by TwoSpacesSG** [shinovon/KEmulator#11]
Now 96x65 and 128x128 versions launch on KEmnnmod, but the LCDUI menu in this particular game is not functional - it returns to the first page approximately every second. Because of this entering the game is not possible.

https://mega.nz/file/51FkXbwD#EffiS1T8gM5gLTIVc_nvsHzqeXhx8XMhuRUkZqR6pzU

**Comment by TwoSpacesSG** [comment]
If I understand correctly from the response in the chat, the issue has been looked into a bit and postponed for now. Can I also direct your attention at version 1.6.12 for 176x220 (couldn't find info on which device it actually is for, maybe Sony Ericsson or Motorola), in which the softkeys don't do anything except create a log entry.

**Comment by shinovon** [comment]
> in which the softkeys don't do anything except create a log entry.
Fixed in 86f84fb

**Comment by TwoSpacesSG** [comment]
Turns out 1.6.12 is for Motorola Triplets devices, and thank you for the workaround introduced.
