### ISSUE TITLE
kemulator.cfg location

### ISSUE THREAD

**Issue by TwoSpacesSG** [shinovon/KEmulator#12]
It was a highly questionable decision of the original KEmu author to make it save kemulator.cfg in every jar folder. I suggest saving one instance of kemulator.cfg in the kemnnmod folder if possible, and you could rename it to something like "platform.txt" for consistency with other KEmulator-created files.

**Comment by shinovon** [comment]
Done in 5cddcf5750fc4089cc64691621135a91189aeeab
