### ISSUE TITLE
Softkeys don't respond in Marble Madness 3D

### ISSUE THREAD

**Issue by TwoSpacesSG** [shinovon/KEmulator#18]
https://mega.nz/file/YhchkJ4S#L0kpppyvaixxVcMKljUosjflPxlBPLoxoRaoTlRgOko

This is a Sony Ericsson preinstalled game with Mascot Capsule and motion sensor APIs. On nnmod it works almost properly, but the  Nokia/SE softkeys don't do anything when pressed. It does not seem like a commands related issue like it was in Harry Potter 3 for Motorola Triplets. Perhaps the game forces the use of SE "gaming keys" for some reason?

**Comment by shinovon** [comment]
Softkeys do work when `device_needs_commands` property in MANIFEST.MF is set to `1`

**Comment by TwoSpacesSG** [comment]
I checked this some time ago and that does seem to fix it, thank you for finding this workaround.
