### ISSUE TITLE
MIDI distortion because of carryover from the previous track

### ISSUE THREAD

**Issue by TwoSpacesSG** [shinovon/KEmulator#23]
BreakQuest Mobile: https://files.seclub.org/game/5/1/6/5162d9f2e6c9cb8aa33cbcb7f04fe0de/BreakQuest_Mobile_SonyEricssonW910i_240x320_Eng_Supplied_By_BerON.jar

Presumably this is the same issue as Shadow Shoot (all versions except the smallest one): https://mega.nz/file/9tdjUIJI#OF-TcKA0lavma3bc_LYmKi6oMFO4ChN3n5LkmPx387k

In BreakQuest Mobile, listen to the title music with its pitch bends. Now go to level 1, then back out to the title (LSK), and the title pitch bends will be all messed up.

In Shadow Shoot, the issue is with the second half of the stages 5-8 theme, it sounds wrong sometimes.

Edit: Sorry, forgot to mention, I'm using the JRE player, not Coolsoft VMS.

**Comment by shinovon** [comment]
Fixed in 5e1aca27bf7733fd0c07bd5718260ad263cf2e60
