### ISSUE TITLE
Ratchet and Clank Going Mobile - game performance seems to depend on PC configuration

### ISSUE THREAD

**Issue by TwoSpacesSG** [shinovon/KEmulator#45]
https://mega.nz/file/19UByIQT#wX4iRK50OIhdq5Fnb5yu25fTSTIMkD_ihCuh2MdvtTc (the 352x416 version for Nokia N80 is of most interest)

Various people over the time have been saying that on the original KEmulator, this 2D game has lag issues. Now I got a report from thaice22 about the following in regards to stable 2.16.2:

If the game is reset with Alt+R (this might be required between playing sessions of this game because it creates a lot of WAV players), it might start with proper performance, or it might start and proceed performing badly: when uncapped, it will run at 65 FPS, when capped to 50 fps using the Max FPS option, it will run at 33 fps. 

I don't have this issue to the same extent: capping fps to 50 will make the game run at 48 FPS (still not perfect), and uncapped it plays at 95.

Shinovon also told me that on his end, the game runs at 85 FPS when uncapped.

Screenshot from thaice22:
![java_mTijrRGU54](https://github.com/shinovon/KEmulator/assets/89545368/ae7325ce-f606-49f4-802e-16b79f793865)

Screenshot from me:
![image](https://github.com/shinovon/KEmulator/assets/89545368/91e40208-904b-4e0c-a97e-811c7026885a)

As an aside, thaice22 says that on his end, every time KEmulator restarts with poor performance, it also restarts with swapped * and # keys (on C and V). However I don't see how this could be possible yet.

**Comment by shinovon** [comment]
0436853fb570c5d281ab42b99027d45fc9b5d19f related

**Comment by TwoSpacesSG** [comment]
Although various people have had these kind of issues with specifically the original KEmulator, the person who reported the above behavior is not part of the community in question anymore as it turns out, and it's not in my interest to track them down individually to ask about KEmulator nnmod performance in the latest build. I have never had any serious performance issue personally if anything. So i don't think there's any point in holding this issue open, honestly, let's just say it's solved.
