### ISSUE TITLE
M3G Viewer is Broken

### ISSUE THREAD

**Issue by iplayfastandfurious** [shinovon/KEmulator#46]
When I try to use M3G Viewer on some games, it breaks. At first it shows the m3g, but when rotated, the m3g completely disappears. It can only be seen at the camera angle shown. Another bug is if the m3g is viewable, it looks like your seeing a picture of that m3g because you cannot zoom in or look around it

**Comment by shinovon** [comment]
Examples?

**Comment by iplayfastandfurious** [comment]
> Examples?

![Screenshot 2024-07-02 152652](https://github.com/shinovon/KEmulator/assets/153218731/86c1ffbc-d9f8-4e5e-af55-f2352ed405ee)
[
![Screenshot 2024-07-02 151848](https://github.com/shinovon/KEmulator/assets/153218731/d90f32e5-53b7-4016-82c9-cd0e15055acf)

](url)

**Comment by shinovon** [comment]
in nnmod controls of m3g view are remade, it is now WASD or in FreeCam mode

**Comment by iplayfastandfurious** [comment]
oh ok thanks
