### ISSUE TITLE
Regarding the multi-language support of the KE.

### ISSUE THREAD

**Issue by Rosabis** [shinovon/KEmulator#47]
I want to add a language I am familiar with to the simulator, but I have some questions that I hope can be answered:
1. As shown in the picture, I found that some options are not in the language file of the simulator located in the lang folder.
![图片](https://github.com/user-attachments/assets/8d18178d-b0f3-4136-ae15-f17d07bd913b)
![无标题](https://github.com/user-attachments/assets/eaf2fb52-ffa5-4d7b-9013-9478e9ee687f)
2. I don’t know where the M3G language files are.
![图片](https://github.com/user-attachments/assets/b385d5d1-758c-48dc-a171-3d307c51a084)

**Comment by shinovon** [comment]
They are unlocalized at the moment
