### ISSUE TITLE
Some things that should be drawn immediately are drawn too late (Mega Man Pinball)

### ISSUE THREAD

**Issue by TwoSpacesSG** [shinovon/KEmulator#58]
This is a small regression that was introduced recently and I'm aware of it affecting [Mega Man Pinball](https://seclub.org/dn.php?d=4&r=3&c=2&fd=2136) and Harry Potter 3 (Nokia 176x208).

In Mega Man Pinball, the flippers should be drawn as soon as the stage starts, but they are only drawn when something touches them.

![2024 08 09_11 14 03_2](https://github.com/user-attachments/assets/96bb7cc1-c841-4929-87a0-c4dcd1ac6144)

In Harry Potter 3, in level 2 of arcade mode, this affects the greenhouse entrances, they only show up when Harry goes under them.

**Comment by shinovon** [comment]
broke after 71a78a5c9325f18d47cd44ee16b9df7787870252
something related to serviceRepaints

**Comment by TwoSpacesSG** [comment]
I checked Mega Man Pinball in the latest dev build and it is fixed there. Haven't gotten to check Harry Potter 3 (level 2) yet, but the beginning of the game works fine in the latest dev build at least.
