### ISSUE TITLE
Ratchet and Clank: Going Mobile (Nokia N80) - firing shots lags the game

### ISSUE THREAD

**Issue by TwoSpacesSG** [shinovon/KEmulator#67]
I believe this is unrelated to the fabled "performance issue". In the level Circuit Circuit, get the ammo for the gun and hold the button to waste it all at once. You will see that there are noticeable lag spikes when firing. This may be related to how this version creates a new WAV player for each shot.

**Comment by TwoSpacesSG** [comment]
There's a sound on/off toggle in the game itself that I believe negates this issue, at the cost of making the game silent. Therefore the force sound off toggle doesn't help this case.

**Comment by shinovon** [comment]
d9efe67131fbc65a806664fa681c4751a870c538 related

**Comment by shinovon** [comment]
Partially fixed by introducing wav cache
