### ISSUE TITLE
Broken canvas titles

### ISSUE THREAD

**Issue by gtrxAC** [shinovon/KEmulator#77]
How to reproduce:
- Go to settings, Core API, and make sure "Ignore Canvas.setFullScreenMode" is disabled
- Run a midlet which uses setTitle() on a Canvas
  - For example JBenchmark 2 (start benchmark and wait for the text drawing test) or [Discord J2ME beta](http://146.59.80.3/discord_midp2_beta.jar) (log in with a dummy token to get to the main menu)

Expected behavior:
- The title text of the Canvas is shown in a bar at the top of the screen, similar to what happens in high-level LCDUI screens like Forms.
- When resizing the emulator window, the title bar shows in the correct location.

Actual behavior:
- There is no title bar at the top of the screen. Instead, there is a white bar at the bottom with no text on it.
- When resizing the emulator window (increasing its height), there are two white bars - one at the original location, and one at the bottom of the resized window.

**Comment by shinovon** [comment]
Closed by e2dab165d6463edc2e18831307bd65078c517f27, 9bdf13fe273239b337d34351e69a0f8956224bcf
