### ISSUE TITLE
javax.microedition.lcdui.Form.insert(int index, Item item) duplicates all items after index

### ISSUE THREAD

**Issue by yegamega** [shinovon/KEmulator#87]
javax.microedition.lcdui.Form.insert(int index, Item item) duplicates all items after index.
Form adds items, but doesnät delete old

**Comment by shinovon** [comment]
Closed by d11acd8b182d5863dd14db856756ff63aac81165, 52e310683e6197e2c9d859d3af48fc24f1f19cbb,
