### ISSUE TITLE
Home Run King 2 - incorrect placement of the gameplay screen

### ISSUE THREAD

**Issue by TwoSpacesSG** [shinovon/KEmulator#92]
Home Run King 2 by Sega should start up with intro logos and proceed to the title/menu screen with music, then the character select screen, then the gameplay. On KEmnn it shows the gameplay for a few seconds instead of the intro logos, then proceeds to the title/menu screen without music, then the character select screen, and then the game freezes. While I don't really care about this game, this issue could be indicative of something that could negatively affect other games.

**Comment by shinovon** [comment]
Problem is in vlc player, disabled amr player for now.
